import json
from copy import deepcopy

SUPPORTED_TAGS = [
    "[clear throat]",
    "[sigh]",
    "[shush]",
    "[cough]",
    "[groan]",
    "[sniff]",
    "[gasp]",
    "[chuckle]",
    "[laugh]",
]

LABEL_TO_TAG = {
    "clear_throat": "[clear throat]",
    "sigh": "[sigh]",
    "shush": "[shush]",
    "cough": "[cough]",
    "groan": "[groan]",
    "sniff": "[sniff]",
    "gasp": "[gasp]",
    "chuckle": "[chuckle]",
    "laugh": "[laugh]",
    "none": "",
}

DEFAULT_CONFIG = {
    "time_style": "12h",
    "time_zero": "oclock",
    "time_include_am_pm": True,
    "minute_leading_zero": "oh",
    "paren_policy": "expand",
    "strip_emoji": True,
    "tagger_enabled": True,
    "tag_min_confidence": 0.3,
    "tag_position": "prefix",
    "url_policy": "domain",
    "url_include_scheme": False,
    "url_read_query": False,
    "url_read_fragment": False,
    "url_include_port": True,
    "path_policy": "speak",
    "ip_digit_style": "single",
    "auto_spell_acronyms": True,
    "acronym_stoplist": [
        "AM",
        "PM",
        "OK",
        "US",
        "UK",
    ],
    "acronym_force": [
        "AI",
        "ML",
        "NLP",
        "LLM",
        "ASR",
        "TTS",
        "API",
        "SDK",
        "HTTP",
        "HTTPS",
        "URL",
        "URI",
        "DNS",
        "IP",
        "TCP",
        "UDP",
        "SSH",
        "SSL",
        "TLS",
        "JSON",
        "XML",
        "HTML",
        "CSS",
        "JS",
        "TS",
        "SQL",
        "GPU",
        "CPU",
        "RAM",
        "VRAM",
        "SSD",
        "HDD",
        "OS",
        "UI",
        "UX",
        "CLI",
        "IDE",
        "CI",
        "CD",
        "QA",
        "SaaS",
        "PaaS",
        "IaaS",
        "IoT",
        "CUDA",
        "C++",
        "C#",
        "F#",
        "RTX",
        "GPT",
        "UUID",
        "GUID",
        "ASCII",
        "UTF",
        "RGB",
        "BGR",
    ],
    "abbreviations": {
        "e.g.": "for example",
        "i.e.": "that is",
        "etc.": "et cetera",
        "vs.": "versus",
        "mr.": "mister",
        "mrs.": "missus",
        "dr.": "doctor",
    },
    "tech_pronunciations": {
        "AI": "a i",
        "ML": "m l",
        "DL": "d l",
        "LLM": "l l m",
        "NLP": "n l p",
        "ASR": "a s r",
        "TTS": "t t s",
        "API": "a p i",
        "SDK": "s d k",
        "HTTP": "h t t p",
        "HTTPS": "h t t p s",
        "URL": "u r l",
        "URI": "u r i",
        "DNS": "d n s",
        "IP": "i p",
        "TCP": "t c p",
        "UDP": "u d p",
        "SSH": "s s h",
        "SSL": "s s l",
        "TLS": "t l s",
        "JSON": "j s o n",
        "XML": "x m l",
        "HTML": "h t m l",
        "CSS": "c s s",
        "JS": "j s",
        "TS": "t s",
        "SQL": "s q l",
        "GPU": "g p u",
        "CPU": "c p u",
        "RAM": "r a m",
        "VRAM": "v r a m",
        "SSD": "s s d",
        "HDD": "h d d",
        "OS": "o s",
        "UI": "u i",
        "UX": "u x",
        "CLI": "c l i",
        "IDE": "i d e",
        "CI": "c i",
        "CD": "c d",
        "CI/CD": "c i slash c d",
        "QA": "q a",
        "SaaS": "s a a s",
        "PaaS": "p a a s",
        "IaaS": "i a a s",
        "IoT": "i o t",
        "CUDA": "koo da",
        "RTX": "r t x",
        "GPT": "g p t",
        "C++": "c plus plus",
        "C#": "c sharp",
        "F#": "f sharp",
        ".NET": "dot net",
        "Node.js": "node j s",
        "Next.js": "next j s",
        "React.js": "react j s",
        "Vue.js": "vue j s",
        "TypeScript": "type script",
        "JavaScript": "java script",
        "K8s": "k eight s",
        "K3s": "k three s",
        "OAuth": "o auth",
        "JWT": "j w t",
        "REST": "r e s t",
        "gRPC": "g r p c",
        "UTF-8": "u t f eight",
        "UTF8": "u t f eight",
        "ASCII": "a s c i i",
    },
    "domain_pronunciations": {
        "com": "com",
        "net": "net",
        "org": "org",
        "io": "i o",
        "ai": "a i",
        "dev": "dev",
        "app": "app",
        "edu": "e d u",
        "gov": "gov",
        "co": "co",
        "us": "u s",
        "uk": "u k",
        "gg": "g g",
        "tv": "t v",
        "me": "me",
        "ly": "l y",
    },
    "unit_pronunciations": {
        "kb": "kilobytes",
        "mb": "megabytes",
        "gb": "gigabytes",
        "tb": "terabytes",
        "kib": "kibibytes",
        "mib": "mebibytes",
        "gib": "gibibytes",
        "tib": "tebibytes",
        "hz": "hertz",
        "khz": "kilohertz",
        "mhz": "megahertz",
        "ghz": "gigahertz",
        "kbps": "kilobits per second",
        "mbps": "megabits per second",
        "gbps": "gigabits per second",
        "ms": "milliseconds",
        "s": "seconds",
        "sec": "seconds",
        "secs": "seconds",
        "min": "minutes",
        "mins": "minutes",
        "hr": "hours",
        "hrs": "hours",
        "fps": "frames per second",
        "dpi": "dots per inch",
        "ppi": "pixels per inch",
        "px": "pixels",
        "%": "percent",
    },
    "allowed_tags": SUPPORTED_TAGS,
    "label_to_tag": LABEL_TO_TAG,
}


def load_config(path):
    if not path:
        return deepcopy(DEFAULT_CONFIG)
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)
    cfg = deepcopy(DEFAULT_CONFIG)
    cfg.update(data)
    return cfg
